version: "3"

services:
  namenode:
    image: lujiefsi/hadoop-namenode:database
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=database
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 9000:9000

  datanode:
    image: lujiefsi/hadoop-datanode:database
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870 namenode:9000"
    env_file:
      - ./hadoop.env
  kms:
    image: lujiefsi/hadoop-kms:database
    container_name: kms
    healthcheck:
      test: nc -z localhost 9600 || exit -1
    environment:
      SERVICE_PRECONDITION: "namenode:9870 namenode:9000"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: lujiefsi/hadoop-resourcemanager:database
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: lujiefsi/hadoop-nodemanager:database
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181

  encryption:
    image: lujiefsi/hadoop-encryption:database
    container_name: encryption
    environment:
      SERVICE_PRECONDITION: "kms:9600 namenode:9000 namenode:9870 datanode:9864"
    healthcheck:
      test: nc -z localhost 17000 || exit -1
    env_file:
      - ./hadoop.env


  hbase-master:
    image: lujiefsi/hbase-master:database
    container_name: hbase-master
    hostname: hbase-master
    healthcheck:
      test: nc -z localhost 16010 || exit -1
      interval: 60s
      timeout: 10000000s
      retries: 1000000
    env_file:
      - ./hbase-distributed-local.env
    environment:
            SERVICE_PRECONDITION: "namenode:9870 namenode:9000  datanode:9864 resourcemanager:8088 zookeeper:2181 encryption:17000"
    ports:
      - 16010:16010

  hbase-region:
    image: lujiefsi/hbase-regionserver:database
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    healthcheck:
      test: nc -z localhost 16030 || exit -1
      interval: 60s
      timeout: 10000000s
      retries: 1000000
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "hbase-master:16010 namenode:9870 datanode:9864 zookeeper:2181"
    ports:
      - 16030:16030
  atlas-server:
    image: lujiefsi/atlas:database-distributed
    container_name: atlas-server
    healthcheck:
      test: nc -z localhost 21000 || exit -1
      interval: 60s
      timeout: 10000000s
      retries: 1000000
    environment:
      SERVICE_PRECONDITION: "solr:8983 zookeeper:2181 kafka:9092 hbase-master:16010 hbase-region:16030"
    ports:
      - "21000:21000"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    healthcheck:
      test: nc -z localhost 9092 || exit -1
    environment:
      KAFKA_CREATE_TOPICS: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  solr:
    image: solr:8.7.0
    container_name: solr
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    depends_on:
      - zookeeper
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
